import pandas as pd
from pptx import Presentation
from pptx.util import Inches

# Load data
data_file = "aggregated_data.csv"
data = pd.read_csv(data_file)

# Create a presentation
prs = Presentation()

# Slide 1: Title Slide
slide = prs.slides.add_slide(prs.slide_layouts[0])
title = slide.shapes.title
subtitle = slide.placeholders[1]

title.text = "Tirana Bus Usage Analysis"
subtitle.text = "Exploring Demographics, Time Slots, and Bus Lines"

# Slide 2: Key Insights
slide = prs.slides.add_slide(prs.slide_layouts[1])
title = slide.shapes.title
content = slide.placeholders[1]

title.text = "Key Insights"
content.text = (
    "• Highest revenue generated by passengers aged 19-60.\n"
    "• Peak time slot: 07:00-10:00.\n"
    "• Bus Line 22 contributes most to total revenue.\n"
)

# Slide 3: Revenue Breakdown by Age Group
slide = prs.slides.add_slide(prs.slide_layouts[5])
title = slide.shapes.title
title.text = "Revenue Breakdown by Age Group"

age_group_revenue = data.groupby("age_group")["total_revenue"].sum()
content = slide.shapes.add_textbox(Inches(1), Inches(1.5), Inches(8), Inches(4))
content.text = age_group_revenue.to_string()

# Slide 4: Revenue Breakdown by Time Slot
slide = prs.slides.add_slide(prs.slide_layouts[5])
title = slide.shapes.title
title.text = "Revenue Breakdown by Time Slot"

time_slot_revenue = data.groupby("time_slot")["total_revenue"].sum()
content = slide.shapes.add_textbox(Inches(1), Inches(1.5), Inches(8), Inches(4))
content.text = time_slot_revenue.to_string()

# Slide 5: Recommendations
slide = prs.slides.add_slide(prs.slide_layouts[1])
title = slide.shapes.title
content = slide.placeholders[1]

title.text = "Recommendations"
content.text = (
    "• Target marketing campaigns for age group 19-60.\n"
    "• Optimize services during peak times (07:00-10:00).\n"
    "• Focus on improving capacity for Bus Line 22.\n"
)

# Save presentation
output_file = "Tirana_Bus_Usage_Analysis.pptx"
prs.save(output_file)
print(f"Presentation saved as {output_file}.")
